### Python Pandas Counting the Occurrences of a Specific value
https://stackoverflow.com/questions/35277075/python-pandas-counting-the-occurrences-of-a-specific-value

### Python Pandas - difference between 'loc' and 'where'?
https://stackoverflow.com/questions/54900717/python-pandas-difference-between-loc-and-where

### Using loc with multiple conditions
https://kanoki.org/2020/01/21/pandas-dataframe-filter-with-multiple-conditions/

### How to use Regex in Pandas
https://kanoki.org/2019/11/12/how-to-use-regex-in-pandas/

### Test Regex
https://regex101.com/

In [15]:
import pandas as pd
import numpy as np

df = pd.read_csv("survey.csv")
num_columns = len(df.columns)
pd.set_option("display.max_columns", num_columns)
df.head(30)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
5,2014-08-27 11:31:22,33,Male,United States,TN,NaN,Yes,No,Sometimes,6-25,No,Yes,Yes,Not sure,No,Don't know,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No,NaN
6,2014-08-27 11:31:50,35,Female,United States,MI,NaN,Yes,Yes,Sometimes,1-5,Yes,Yes,No,No,No,No,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No,NaN
7,2014-08-27 11:32:05,39,M,Canada,NaN,NaN,No,No,Never,1-5,Yes,Yes,No,Yes,No,No,Yes,Don't know,No,No,No,No,No,No,No,No,NaN
8,2014-08-27 11:32:39,42,Female,United States,IL,NaN,Yes,Yes,Sometimes,100-500,No,Yes,Yes,Yes,No,No,No,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No,NaN
9,2014-08-27 11:32:43,23,Male,Canada,NaN,NaN,No,No,Never,26-100,No,Yes,Don't know,No,Don't know,Don't know,Don't know,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
10,2014-08-27 11:32:44,31,Male,United States,OH,NaN,No,Yes,Sometimes,6-25,Yes,Yes,Don't know,No,No,No,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,NaN
11,2014-08-27 11:32:49,29,male,Bulgaria,NaN,NaN,No,No,Never,100-500,Yes,Yes,Don't know,Not sure,No,No,Don't know,Don't know,No,No,Yes,Yes,Yes,Yes,Don't know,No,NaN
12,2014-08-27 11:33:23,42,female,United States,CA,NaN,Yes,Yes,Sometimes,26-100,No,No,Yes,Yes,No,No,Don't know,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes,NaN
13,2014-08-27 11:33:26,36,Male,United States,CT,NaN,Yes,No,Never,500-1000,No,Yes,Don't know,Not sure,No,Don't know,Don't know,Don't know,No,No,Yes,Yes,No,No,Don't know,No,I'm not on my company's health insurance which...
14,2014-08-27 11:33:57,27,Male,Canada,NaN,NaN,No,No,Never,6-25,No,Yes,Don't know,Not sure,Don't know,Don't know,Don't know,Somewhat easy,No,No,Some of them,Some of them,Maybe,Yes,Yes,No,NaN
15,2014-08-27 11:34:00,29,female,United States,IL,NaN,Yes,Yes,Rarely,26-100,No,Yes,Yes,Not sure,No,No,Don't know,Somewhat easy,No,No,Yes,Some of them,Maybe,Maybe,Don't know,No,I have chronic low-level neurological issues t...
16,2014-08-27 11:34:20,23,Male,United Kingdom,NaN,NaN,No,Yes,Sometimes,26-100,Yes,Yes,Don't know,No,Don't know,Don't know,Don't know,Very easy,Maybe,No,Some of them,No,Maybe,Maybe,No,No,My company does provide healthcare but not to ...
17,2014-08-27 11:34:37,32,Male,United States,TN,NaN,No,Yes,Sometimes,6-25,No,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Maybe,No,Some of them,Yes,No,No,No,No,NaN
18,2014-08-27 11:34:53,46,male,United States,MD,Yes,Yes,No,Sometimes,1-5,Yes,Yes,Yes,Not sure,Yes,Don't know,Yes,Very easy,No,No,Yes,Yes,No,Yes,Yes,Yes,NaN
19,2014-08-27 11:35:08,36,Male,France,NaN,Yes,Yes,No,NaN,6-25,Yes,Yes,No,No,Yes,No,Yes,Somewhat easy,No,No,Some of them,Some of them,Maybe,Maybe,Don't know,No,NaN
20,2014-08-27 11:35:12,29,Male,United States,NY,No,Yes,Yes,Sometimes,100-500,No,Yes,Yes,Yes,No,No,No,Somewhat difficult,Maybe,No,Some of them,Some of them,No,No,No,No,NaN
21,2014-08-27 11:35:24,31,male,United States,NC,Yes,No,No,Never,1-5,Yes,Yes,No,No,No,No,Yes,Somewhat difficult,No,No,Some of them,Some of them,No,Maybe,Yes,No,NaN
22,2014-08-27 11:35:48,46,Male,United States,MA,No,No,Yes,Often,26-100,Yes,Yes,Yes,Yes,No,No,Don't know,Don't know,Maybe,No,Some of them,Yes,No,Maybe,No,No,NaN
23,2014-08-27 11:36:24,41,Male,United States,IA,No,No,Yes,Never,More than 1000,No,No,Don't know,No,No,Don't know,Don't know,Don't know,Maybe,No,No,No,No,Yes,Don't know,No,NaN
24,2014-08-27 11:36:48,33,male,United States,CA,No,Yes,Yes,Rarely,26-100,No,Yes,Yes,Not sure,Don't know,Yes,Yes,Don't know,No,No,Yes,Yes,No,Yes,Don't know,No,Relatively new job. Ask again later
25,2014-08-27 11:37:08,35,male,United States,TN,No,Yes,Yes,Sometimes,More than 1000,No,No,Yes,Yes,No,Don't know,No,Very easy,Yes,No,Some of them,Yes,No,Yes,No,No,Sometimes I think about using drugs for my me...
26,2014-08-27 11:37:23,33,male,United States,TN,No,No,No,NaN,1-5,No,Yes,Don't know,Not sure,No,Don't know,Don't know,Don't know,Maybe,Maybe,Some of them,No,No,No,Don't know,No,NaN
27,2014-08-27 11:37:59,35,Female,United States,CA,No,Yes,Yes,Rarely,6-25,Yes,Yes,Yes,Yes,Don't know,Don't know,Don't know,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
28,2014-08-27 11:38:12,34,male,United States,OH,No,No,Yes,Sometimes,26-100,Yes,Yes,Don't know,Not sure,No,Don't know,Don't know,Somewhat difficult,No,No,Some of them,No,No,No,No,No,NaN
29,2014-08-27 11:38:18,37,Male,United Kingdom,NaN,No,No,No,Sometimes,6-25,No,Yes,No,No,No,No,Don't know,Very difficult,Yes,Maybe,Some of them,No,No,Maybe,No,No,NaN

In [16]:
feature_names = df.columns.tolist()
feature_names.remove('Timestamp')
feature_names.remove('comments')

for column in feature_names:
    print("\n\n*************Column:*************", column)
    print(df[column].value_counts(dropna=False))

*************Column:************* Age
 29             85
 32             82
 26             75
 27             71
 33             70
 28             68
 31             67
 34             65
 30             63
 25             61
 35             55
 23             51
 24             46
 37             43
 38             39
 36             37
 39             33
 40             33
 43             28
 41             21
 22             21
 42             20
 21             16
 45             12
 46             12
 44             11
 19              9
 18              7
 20              6
 48              6
 50              6
 51              5
 56              4
 49              4
 57              3
 54              3
 55              3
 47              2
 60              2
 11              1
 8               1
 5               1
 99999999999     1
-1726            1
 53              1
 58              1
 61              1
 62              1
 65              1
 72              1
 329             1
-29              1
-1               1
Name: Age, dtype: int64


*************Column:************* Gender
Male                                              615
male                                              206
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Woman                                               3
Male                                                3
Female                                              2
Man                                                 2
Cis Male                                            2
Female (trans)                                      2
A little about you                                  1
cis male                                            1
Genderqueer                                         1
Female (cis)                                        1
Cis Man                                             1
queer                                               1
Neuter                                              1
Male-ish                                            1
Malr                                                1
Mail                                                1
male leaning androgynous                            1
Cis Female                                          1
Femake                                              1
Mal                                                 1
non-binary                                          1
All                                                 1
Nah                                                 1
msle                                                1
Agender                                             1
Trans-female                                        1
p                                                   1
Androgyne                                           1
Trans woman                                         1
cis-female/femme                                    1
queer/she/they                                      1
woman                                               1
Male (CIS)                                          1
maile                                               1
Enby                                                1
fluid                                               1
something kinda male?                               1
femail                                              1
Guy (-ish) ^_^                                      1
ostensibly male, unsure what that really means      1
Name: Gender, dtype: int64


*************Column:************* Country
United States             751
United Kingdom            185
Canada                     72
Germany                    45
Ireland                    27
Netherlands                27
Australia                  21
France                     13
India                      10
New Zealand                 8
Poland                      7
Italy                       7
Sweden                      7
Switzerland                 7
Belgium                     6
South Africa                6
Brazil                      6
Israel                      5
Singapore                   4
Bulgaria                    4
Russia                      3
Finland                     3
Mexico                      3
Austria                     3
Croatia                     2
Portugal                    2
Denmark                     2
Greece                      2
Colombia                    2
Latvia                      1
Uruguay                     1
Georgia                     1
Nigeria                     1
Thailand                    1
Bahamas, The                1
Philippines                 1
Japan                       1
Moldova                     1
Hungary                     1
Zimbabwe                    1
Norway                      1
Bosnia and Herzegovina      1
Costa Rica                  1
Slovenia                    1
Spain                       1
Romania                     1
Czech Republic              1
China                       1
Name: Country, dtype: int64


*************Column:************* state
NaN    515
CA     138
WA      70
NY      57
TN      45
TX      44
OH      30
OR      29
IL      29
PA      29
IN      27
MI      22
MN      21
MA      20
FL      15
NC      14
VA      14
MO      12
GA      12
WI      12
UT      11
CO       9
AL       8
MD       8
AZ       7
NJ       6
OK       6
KY       5
SC       5
IA       4
DC       4
CT       4
SD       3
VT       3
KS       3
NV       3
NH       3
NE       2
WY       2
NM       2
ME       1
MS       1
WV       1
LA       1
ID       1
RI       1
Name: state, dtype: int64


*************Column:************* self_employed
No     1095
Yes     146
NaN      18
Name: self_employed, dtype: int64


*************Column:************* family_history
No     767
Yes    492
Name: family_history, dtype: int64


*************Column:************* treatment
Yes    637
No     622
Name: treatment, dtype: int64


*************Column:************* work_interfere
Sometimes    465
NaN          264
Never        213
Rarely       173
Often        144
Name: work_interfere, dtype: int64


*************Column:************* no_employees
6-25              290
26-100            289
More than 1000    282
100-500           176
1-5               162
500-1000           60
Name: no_employees, dtype: int64


*************Column:************* remote_work
No     883
Yes    376
Name: remote_work, dtype: int64


*************Column:************* tech_company
Yes    1031
No      228
Name: tech_company, dtype: int64


*************Column:************* benefits
Yes           477
Don't know    408
No            374
Name: benefits, dtype: int64


*************Column:************* care_options
No          501
Yes         444
Not sure    314
Name: care_options, dtype: int64


*************Column:************* wellness_program
No            842
Yes           229
Don't know    188
Name: wellness_program, dtype: int64


*************Column:************* seek_help
No            646
Don't know    363
Yes           250
Name: seek_help, dtype: int64


*************Column:************* anonymity
Don't know    819
Yes           375
No             65
Name: anonymity, dtype: int64


*************Column:************* leave
Don't know            563
Somewhat easy         266
Very easy             206
Somewhat difficult    126
Very difficult         98
Name: leave, dtype: int64


*************Column:************* mental_health_consequence
No       490
Maybe    477
Yes      292
Name: mental_health_consequence, dtype: int64


*************Column:************* phys_health_consequence
No       925
Maybe    273
Yes       61
Name: phys_health_consequence, dtype: int64


*************Column:************* coworkers
Some of them    774
No              260
Yes             225
Name: coworkers, dtype: int64


*************Column:************* supervisor
Yes             516
No              393
Some of them    350
Name: supervisor, dtype: int64


*************Column:************* mental_health_interview
No       1008
Maybe     207
Yes        44
Name: mental_health_interview, dtype: int64


*************Column:************* phys_health_interview
Maybe    557
No       500
Yes      202
Name: phys_health_interview, dtype: int64


*************Column:************* mental_vs_physical
Don't know    576
Yes           343
No            340
Name: mental_vs_physical, dtype: int64


*************Column:************* obs_consequence
No     1075
Yes     184
Name: obs_consequence, dtype: int64

In [22]:
features = df.drop('treatment', 1)
features = features.drop('Timestamp', 1)
features = features.drop('comments', 1)
labels = df['treatment']

In [23]:
from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#imputer = SimpleImputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = SimpleImputer(missing_values = 'NaN', strategy = 'mean')
imputer.fit(features) 
features = imputer.transform(features)

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'Female'